/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jotldnepqmorpstdqwhz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdGxkbmVwcW1vcnBzdGRxd2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzODg5NTYsImV4cCI6MjEwMzk2NDk1Nn0.aPwjJk4Bc-PRc-TD4B5Fv_LeLjjJs-Dr3eBKM4pZw1U"